# Generated by Django 2.0 on 2019-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("exercises", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="professor", name="age", field=models.IntegerField(default=18)
        )
    ]
